// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehiclePartsAPI.Data;

#nullable disable

namespace VehiclePartsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428192018_SeedParts")]
    partial class SeedParts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehiclePartsAPI.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCreditDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PendingCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("integer");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Filters",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9494),
                            Description = "High quality engine oil filter for all vehicles",
                            IsActive = true,
                            Name = "Engine Oil Filter",
                            PurchasePrice = 350.00m,
                            ReorderLevel = 10,
                            SKU = "EOF-001",
                            SellingPrice = 450.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 2,
                            Category = "Brakes",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9497),
                            Description = "Front brake pads for sedan and hatchback",
                            IsActive = true,
                            Name = "Brake Pads (Front)",
                            PurchasePrice = 1200.00m,
                            ReorderLevel = 10,
                            SKU = "BPF-002",
                            SellingPrice = 1500.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 3,
                            Category = "Ignition",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9499),
                            Description = "NGK spark plugs set of 4",
                            IsActive = true,
                            Name = "Spark Plug (Set of 4)",
                            PurchasePrice = 800.00m,
                            ReorderLevel = 10,
                            SKU = "SPK-003",
                            SellingPrice = 1000.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 4,
                            Category = "Filters",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9501),
                            Description = "Engine air filter for better performance",
                            IsActive = true,
                            Name = "Air Filter",
                            PurchasePrice = 250.00m,
                            ReorderLevel = 10,
                            SKU = "AF-004",
                            SellingPrice = 350.00m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 5,
                            Category = "Clutch",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9503),
                            Description = "Heavy duty clutch plate",
                            IsActive = true,
                            Name = "Clutch Plate",
                            PurchasePrice = 2500.00m,
                            ReorderLevel = 10,
                            SKU = "CLP-005",
                            SellingPrice = 3000.00m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 6,
                            Category = "Lighting",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9505),
                            Description = "H4 halogen headlight bulb",
                            IsActive = true,
                            Name = "Headlight Bulb (H4)",
                            PurchasePrice = 150.00m,
                            ReorderLevel = 10,
                            SKU = "HLB-006",
                            SellingPrice = 200.00m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 7,
                            Category = "Cooling",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9507),
                            Description = "Engine coolant 1L bottle",
                            IsActive = true,
                            Name = "Radiator Coolant",
                            PurchasePrice = 450.00m,
                            ReorderLevel = 10,
                            SKU = "RDC-007",
                            SellingPrice = 550.00m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 8,
                            Category = "Wheel",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9593),
                            Description = "Front wheel bearing",
                            IsActive = true,
                            Name = "Wheel Bearing",
                            PurchasePrice = 800.00m,
                            ReorderLevel = 10,
                            SKU = "WHB-008",
                            SellingPrice = 1000.00m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 9,
                            Category = "Filters",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9596),
                            Description = "Fuel filter for diesel and petrol engines",
                            IsActive = true,
                            Name = "Fuel Filter",
                            PurchasePrice = 300.00m,
                            ReorderLevel = 10,
                            SKU = "FF-009",
                            SellingPrice = 400.00m,
                            StockQuantity = 16
                        },
                        new
                        {
                            Id = 10,
                            Category = "Suspension",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9599),
                            Description = "Front shock absorber",
                            IsActive = true,
                            Name = "Shock Absorber (Front)",
                            PurchasePrice = 1800.00m,
                            ReorderLevel = 10,
                            SKU = "SHA-010",
                            SellingPrice = 2200.00m,
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 11,
                            Category = "Electrical",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9601),
                            Description = "12V alternator for most cars",
                            IsActive = true,
                            Name = "Alternator",
                            PurchasePrice = 4500.00m,
                            ReorderLevel = 10,
                            SKU = "ALT-011",
                            SellingPrice = 5500.00m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = 12,
                            Category = "Electrical",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9603),
                            Description = "12V starter motor",
                            IsActive = true,
                            Name = "Starter Motor",
                            PurchasePrice = 3500.00m,
                            ReorderLevel = 10,
                            SKU = "STM-012",
                            SellingPrice = 4200.00m,
                            StockQuantity = 2
                        },
                        new
                        {
                            Id = 13,
                            Category = "Engine",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9605),
                            Description = "Timing belt for 4 cylinder engines",
                            IsActive = true,
                            Name = "Timing Belt",
                            PurchasePrice = 1200.00m,
                            ReorderLevel = 10,
                            SKU = "TMB-013",
                            SellingPrice = 1500.00m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = 14,
                            Category = "Brakes",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9608),
                            Description = "Front brake disc rotor",
                            IsActive = true,
                            Name = "Brake Disc (Front)",
                            PurchasePrice = 2200.00m,
                            ReorderLevel = 10,
                            SKU = "BRD-014",
                            SellingPrice = 2800.00m,
                            StockQuantity = 4
                        },
                        new
                        {
                            Id = 15,
                            Category = "Cooling",
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9706),
                            Description = "Engine water pump",
                            IsActive = true,
                            Name = "Water Pump",
                            PurchasePrice = 1800.00m,
                            ReorderLevel = 10,
                            SKU = "WTP-015",
                            SellingPrice = 2300.00m,
                            StockQuantity = 6
                        });
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.PartRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("PartRequests");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.PurchaseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("VendorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.PurchaseInvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<int>("PurchaseInvoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("PurchaseInvoiceId");

                    b.ToTable("PurchaseInvoiceItems");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.SaleInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StaffId");

                    b.ToTable("SaleInvoices");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.SaleInvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PartId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SaleInvoiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PartId");

                    b.HasIndex("SaleInvoiceId");

                    b.ToTable("SaleInvoiceItems");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 28, 19, 20, 18, 242, DateTimeKind.Utc).AddTicks(9066),
                            Email = "admin@vehicleparts.com",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$4D.tfl0rg7eAxwNBGaOVUu0mrDl7iEdXrDFgz7ap4OgrIxFUbMNh6",
                            Phone = "9800000000",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VehicleNumber")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Appointment", b =>
                {
                    b.HasOne("VehiclePartsAPI.Models.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Customer", b =>
                {
                    b.HasOne("VehiclePartsAPI.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("VehiclePartsAPI.Models.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.PartRequest", b =>
                {
                    b.HasOne("VehiclePartsAPI.Models.Customer", "Customer")
                        .WithMany("PartRequests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.PurchaseInvoice", b =>
                {
                    b.HasOne("VehiclePartsAPI.Models.Vendor", "Vendor")
                        .WithMany("PurchaseInvoices")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.PurchaseInvoiceItem", b =>
                {
                    b.HasOne("VehiclePartsAPI.Models.Part", "Part")
                        .WithMany("PurchaseInvoiceItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehiclePartsAPI.Models.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("PurchaseInvoice");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Review", b =>
                {
                    b.HasOne("VehiclePartsAPI.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.SaleInvoice", b =>
                {
                    b.HasOne("VehiclePartsAPI.Models.Customer", "Customer")
                        .WithMany("SaleInvoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehiclePartsAPI.Models.Staff", "Staff")
                        .WithMany("SaleInvoices")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.SaleInvoiceItem", b =>
                {
                    b.HasOne("VehiclePartsAPI.Models.Part", "Part")
                        .WithMany("SaleInvoiceItems")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehiclePartsAPI.Models.SaleInvoice", "SaleInvoice")
                        .WithMany("Items")
                        .HasForeignKey("SaleInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("SaleInvoice");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Staff", b =>
                {
                    b.HasOne("VehiclePartsAPI.Models.User", "User")
                        .WithOne("Staff")
                        .HasForeignKey("VehiclePartsAPI.Models.Staff", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Vehicle", b =>
                {
                    b.HasOne("VehiclePartsAPI.Models.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("PartRequests");

                    b.Navigation("Reviews");

                    b.Navigation("SaleInvoices");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Part", b =>
                {
                    b.Navigation("PurchaseInvoiceItems");

                    b.Navigation("SaleInvoiceItems");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.PurchaseInvoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.SaleInvoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Staff", b =>
                {
                    b.Navigation("SaleInvoices");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.User", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("VehiclePartsAPI.Models.Vendor", b =>
                {
                    b.Navigation("PurchaseInvoices");
                });
#pragma warning restore 612, 618
        }
    }
}
